/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookReader = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData books = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helpCenter = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData portfolio = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trade = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}